[build]
builder = "NIXPACKS"
watchPatterns = ["**"]
buildCommand = "yarn build"
nixpacksConfigPath = "nixpacks.toml"
nixpacksPlan = "examples/node"

[deploy]
startCommand = "yarn start"
numReplicas = 1
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1
