apiVersion: v1
kind: page
spec:
  id: I1HlSLD
  title: joyUiNpmKpis
  display: shell
  queries:
    - name: queryJoyUIDownloads
      query:
        function: queryJoyUIDownloads
        kind: local
  content:
    - component: Text
      name: text
      children: []
      layout:
        columnSize: 1
      props:
        value: Joy UI npm downloads
        variant: h6
    - component: Chart
      name: chart
      children: []
      layout:
        columnSize: 1
      props:
        data:
          - label: "@mui/joy"
            kind: line
            data:
              $$jsExpression: |
                queryJoyUIDownloads.data
            color: "#1976d2"
            xKey: date
            yKey: "@mui/joy"
    - component: Text
      name: text1
      children: []
      layout:
        columnSize: 1
      props:
        value: Joy UI month to month growth (%)
        variant: h6
    - component: Chart
      name: chart1
      children: []
      layout:
        columnSize: 1
      props:
        data:
          - label: "@mui/joy"
            kind: line
            data:
              $$jsExpression: |
                queryJoyUIDownloads.data
                  .map((item, idx) => {
                    return {
                      date: item.date,
                      "@mui/joy":
                        idx > 0
                          ? ((item["@mui/joy"] -
                              queryJoyUIDownloads.data[idx - 1]["@mui/joy"]) /
                              queryJoyUIDownloads.data[idx - 1]["@mui/joy"]) *
                            100
                          : null,
                    }
                  })
                  .filter((item) => item["@mui/joy"] !== null)
            color: "#1976d2"
            xKey: date
            yKey: "@mui/joy"
