apiVersion: v1
kind: page
spec:
  id: ZGrUwtd
  title: gender
  parameters:
    - name: department
      value: ""
  content:
    - component: codeComponent.HealthBadge
      name: codeComponent_HealthBadge
      children: []
      layout:
        columnSize: 1
      props:
        value:
          $$jsExpression: >
            gender1.data != null ? Math.round(gender1.data * 10) / 10 : undefined
        warning: 14
        problem: 7
        lowerIsBetter: false
  queries:
    - name: gender1
      query:
        function: queryGender
        kind: local
      parameters:
        - name: department
          value: Engineering
  display: shell
