apiVersion: v1
kind: page
spec:
  id: 8n03iat
  title: overdueRatio
  content:
    - component: codeComponent.HealthBadge
      name: codeComponent_HealthBadge
      children: []
      layout:
        columnSize: 1
      props:
        warning: 9
        problem: 11
        lowerIsBetter: true
        value:
          $$jsExpression: |
            Math.round(getRatio.data.ratio * 10000) / 100
    - component: Text
      name: Text
      children: []
      layout:
        columnSize: 1
      props:
        value: Based on last 30 days invoices
  queries:
    - name: getRatio
      query:
        function: getRatio
        kind: local
  display: shell
